implementación de pasarela de pago para membresía
Aparking/AparKing_Backend pull request #213
Opened 2024-04-07 18:14 UTC by alepervaz

![Captura de pantalla 2024-04-07 200607](https://github.com/Aparking/AparKing_Backend/assets/73081268/1313ede2-ec66-46ab-9e6a-29ab41699f27)
![Captura de pantalla 2024-04-07 200532](https://github.com/Aparking/AparKing_Backend/assets/73081268/29c2908e-2833-478e-b27d-c2d48b3f21b1)
![Captura de pantalla 2024-04-07 200523](https://github.com/Aparking/AparKing_Backend/assets/73081268/37718269-8c6a-46c2-a2fa-10696776deca)
Implementación de pasarela de pago que incluye la lógica mediante la cual se otorga a los usuarios los créditos y los permisos necesarios

2024-04-07 18:31 UTC, CarmenRuizPorcel requested changes
No se debería hacer la pull request a la épica de planes de precio?

2024-04-07 19:20 UTC, marvicmar commented
Por cierto no olvides de asignar las pull al milestone correspondiente, y opino como Carmen intenta modificar la rama de develop a su épica.

2024-04-08 04:28 UTC, sergiosant02 approved these changes
Muy bien hecho, esta todo perfecto

2024-04-08 15:47 UTC, MarioArocaPaez approved these changes
Buen trabajo

2024-04-09 08:08 UTC, CarmenRuizPorcel approved these changes

2024-04-09 08:09 UTC, merged