Feat/maps in real time implementation/15
Aparking/AparKing_Backend pull request #70
Opened 2024-03-02 07:41 UTC by sergiosant02

He diseñado los endPoints de los parking, para poder, crear, asignar, transferir y eliminar los parking. A su vez también esta diseñada la interfaz de webSocket, se actualiza cuando se crea, elimina o asigna un parking. En caso de eliminar el webSocket solo envía el id para que el frontend se elimine de su lista, pero si lo esta creando, se envía toda la información del parking, para que pueda ser añadido y mostrado en el lado del cliente.

Para emplear websocket será necesario el comando:
docker run --rm -p 6379:6379 redis:7

A su vez para todos estos cambios son necesarias las adaptaciones pertinentes provistas de la documentación de django https://docs.djangoproject.com/en/5.0/ref/contrib/gis/tutorial/ para el correcto funcionamiento de Postgres junto con GIS

2024-03-02 19:44 UTC, ivasansan1 commented
@sergiosant02  el nombre de la rama no sigue las buenas practicas planteadas en el documento de gestión de la configuración planteado por el equipo. Hay se especifica como de debe de nombrar la el nombre de la rama.

2024-03-03 17:08 UTC, JuanCarlosRL commented
He probado lo implementado y parece que todo funciona bien.

Procedo a implementar los test para las funcionalidades añadidas tal y como indico en la issue #81.

2024-03-03 19:18 UTC, CarmenRuizPorcel reviewed
@sergiosant02 tienes que seguir lo que se dice en el documento de configuration management, esto se debería hacer push a la epica y después de la epica a develop. En tu caso seria a la epica de Gestión de espacios de aparcamiento #14

2024-03-03 19:21 UTC, CarmenRuizPorcel requested changes
@sergiosant02 tienes que seguir lo que se dice en el documento de configuration management, esto se debería hacer push a la epica y después de la epica a develop. En tu caso seria a la epica de Gestión de espacios de aparcamiento #14

2024-03-04 18:38 UTC, closed without merging